[package]
name = "teraform"
version = "0.2.0"
authors = ["Zsombor Gegesy <gzsombor@gmail.com>"]
edition = "2024"
description = "Templating engine for the command line"
repository = "https://github.com/gzsombor/teraform"
keywords = ["template", "tera", "cli"]
license = "MIT/Apache-2.0"

[dependencies]
tera = "2.0"
clap = "4.6"
thiserror = "2"
